# Generated by Django 4.1.5 on 2023-01-30 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bureau',
            fields=[
                ('IDF_Bureau', models.IntegerField(primary_key=True, serialize=False)),
                ('Commune', models.CharField(max_length=50)),
                ('Daira', models.CharField(max_length=50)),
                ('Wilaya', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('IDF_Pays', models.IntegerField(primary_key=True, serialize=False)),
                ('Pays', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Registre',
            fields=[
                ('NumReg', models.IntegerField(primary_key=True, serialize=False)),
                ('TypeReg', models.CharField(max_length=50)),
                ('AnneeReg', models.IntegerField()),
                ('NbrActe', models.IntegerField(null=True)),
                ('Bureau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Eadministration.bureau')),
            ],
        ),
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('NumEnr', models.AutoField(primary_key=True, serialize=False)),
                ('N_Personnel', models.IntegerField(null=True)),
                ('Nom', models.CharField(max_length=50, null=True)),
                ('Prenom', models.CharField(max_length=50, null=True)),
                ('Sexe', models.CharField(max_length=1, null=True)),
                ('DateNaiss', models.DateField(null=True)),
                ('AnneeNaiss', models.IntegerField(null=True)),
                ('HeureNaiss', models.TimeField(null=True)),
                ('LieuNaiss', models.CharField(max_length=50, null=True)),
                ('EtatCivil', models.CharField(max_length=50, null=True)),
                ('Adresse', models.CharField(max_length=50, null=True)),
                ('Profession', models.CharField(max_length=50, null=True)),
                ('NumPere', models.IntegerField(null=True)),
                ('NumMere', models.IntegerField(null=True)),
                ('NumReg', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Eadministration.registre')),
            ],
        ),
        migrations.CreateModel(
            name='Officier',
            fields=[
                ('IDF_Officier', models.AutoField(primary_key=True, serialize=False)),
                ('Nom', models.CharField(max_length=50)),
                ('Prenom', models.CharField(max_length=50)),
                ('DatePrise', models.DateField()),
                ('motpass', models.CharField(max_length=16)),
                ('IDF_Bureau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Eadministration.bureau')),
            ],
        ),
        migrations.CreateModel(
            name='Maire',
            fields=[
                ('IDF_Maire', models.IntegerField(primary_key=True, serialize=False)),
                ('Nom', models.CharField(max_length=50)),
                ('Prenom', models.CharField(max_length=50)),
                ('DatePrise', models.DateField()),
                ('motpass', models.CharField(max_length=16)),
                ('IDF_Bureau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Eadministration.bureau')),
            ],
        ),
        migrations.CreateModel(
            name='Consulat',
            fields=[
                ('IDF_Consulate', models.IntegerField(primary_key=True, serialize=False)),
                ('Consulat', models.CharField(max_length=50)),
                ('Ville', models.CharField(max_length=50, null=True)),
                ('IDF_Pays', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Eadministration.pays')),
            ],
        ),
        migrations.CreateModel(
            name='AgentDiplomatique',
            fields=[
                ('IDF_Agent', models.IntegerField(primary_key=True, serialize=False)),
                ('Nom', models.CharField(max_length=50)),
                ('Prenom', models.CharField(max_length=50)),
                ('motpass', models.CharField(max_length=16)),
                ('IDF_Consulat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Eadministration.consulat')),
            ],
        ),
        migrations.CreateModel(
            name='ActeNaissance',
            fields=[
                ('NumNaiss', models.IntegerField(primary_key=True, serialize=False)),
                ('Nom', models.CharField(max_length=50, null=True)),
                ('Prenom', models.CharField(max_length=50, null=True)),
                ('Sexe', models.CharField(max_length=1, null=True)),
                ('DateNaiss', models.DateField(null=True)),
                ('HeureNaiss', models.TimeField(null=True)),
                ('LieuNaiss', models.CharField(max_length=50, null=True)),
                ('Commune', models.CharField(max_length=50, null=True)),
                ('Daira', models.CharField(max_length=50, null=True)),
                ('Wilaya', models.CharField(max_length=50, null=True)),
                ('NomPrenomPere', models.CharField(max_length=50, null=True)),
                ('NomPrenomMere', models.CharField(max_length=50, null=True)),
                ('ProfessionPere', models.CharField(max_length=50, null=True)),
                ('ProfessionMere', models.CharField(max_length=50, null=True)),
                ('LieuNaissPere', models.CharField(max_length=50, null=True)),
                ('LieuNaissMere', models.CharField(max_length=50, null=True)),
                ('DateNaissPere', models.DateField(null=True)),
                ('DateNaissMere', models.DateField(null=True)),
                ('Adresse', models.CharField(max_length=50, null=True)),
                ('MentionMarginale', models.CharField(max_length=200, null=True)),
                ('NumEnr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Eadministration.personne')),
                ('NumReg', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Eadministration.registre')),
            ],
        ),
        migrations.CreateModel(
            name='ActeMariage',
            fields=[
                ('NumMariage', models.IntegerField(primary_key=True, serialize=False)),
                ('DateMar', models.DateField(null=True)),
                ('LieuMar', models.CharField(max_length=50)),
                ('NumEpx', models.IntegerField(null=True)),
                ('NumEps', models.IntegerField(null=True)),
                ('NomEpx', models.CharField(max_length=50)),
                ('PrenomEpx', models.CharField(max_length=50)),
                ('NomEps', models.CharField(max_length=50)),
                ('PrenomEps', models.CharField(max_length=50)),
                ('AdrEpx', models.CharField(max_length=50)),
                ('AdrEps', models.CharField(max_length=50)),
                ('ProfessionEpx', models.CharField(max_length=50)),
                ('ProfessionEps', models.CharField(max_length=50)),
                ('ExistanceContrat', models.CharField(max_length=100)),
                ('NumReg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Eadministration.registre')),
            ],
        ),
        migrations.CreateModel(
            name='ActeDeces',
            fields=[
                ('NumDeces', models.AutoField(primary_key=True, serialize=False)),
                ('DateDeces', models.DateField(null=True)),
                ('HeureDeces', models.TimeField(null=True)),
                ('LieuDeces', models.CharField(max_length=50, null=True)),
                ('EtatCivil', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Eadministration.personne')),
                ('NumReg', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Eadministration.registre')),
            ],
        ),
    ]
