# Generated by Django 4.1.5 on 2023-01-29 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eadministration', '0002_alter_actedeces_etatcivil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actedeces',
            name='NumPersonne',
        ),
    ]
