# Generated by Django 4.1.5 on 2023-01-29 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eadministration', '0003_remove_actedeces_numpersonne'),
    ]

    operations = [
        migrations.AddField(
            model_name='registre',
            name='NbrActe',
            field=models.IntegerField(default=4444),
            preserve_default=False,
        ),
    ]
