# Generated by Django 4.1.5 on 2023-01-29 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eadministration', '0004_registre_nbracte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registre',
            name='NbrActe',
            field=models.IntegerField(null=True),
        ),
    ]
